### ISSUE TITLE
Novelan with FW3.78

### ISSUE THREAD

**Issue by RookieRon** [coolchip/NovelanPy#1]
The program is exactly what I need to monitor my heating pump. Unfortunately, it does not work right out the box.
My hardware is a novelan sole-heating pump, firmware 3.78. With this, the program says in the line "return tnames._make(struct.unpack(fmt, recv_msg))" that the numbers of format and message don't match. My heating pump delivers 928byte. 
Thats why I needed to adjust it a little to make at least the command 3004 working. I compared the values with the android app and adjusted the namedtupels a little.
About command 3003 and 3002 I didn't care since I do not use them right now. 

I attach the edited files here since I'm not familiar with github and don't know how to open a new branch.
Anyway, thank you Sebastian for this work, I was already afraid that I need to adapt some java code or C-Code to python
[WP_Datenlogger.zip](https://github.com/coolchip/NovelanPy/files/3423387/WP_Datenlogger.zip)

**Comment by CBAMav** [comment]
hello. is there already a newer version of this? I have since yesterday a new firmware on it that no longer has the Java app but a web interface. Unfortunately the bytes that come back do not match the version from the git and the zip.  Unfortunately I know almost no python, so I can not manage alone.

i get 928 and 4492 bytes back

after a lot of tries with no luck, i switched to https://pypi.org/project/luxtronik/

**Comment by RookieRon** [comment]
My logging software is running on a Raspberry where Python was already installed. So I made the program run caring about the given errors. 
Since I only code in Python from time to time and only wanted to pull some certain data from the Novelan, I didn't put much effort in it once it did run. I'm more of a user than of a developper.
In other words: I'm afraid that I'm not a big help :-)

**Comment by coolchip** [comment]
Sorry, this was only a litte test project for me. Feel free to modify it. Or try the one from pypi. Happy new year.
